version: "3.9"

services:
  kubify:
    build:
      network: host
    working_dir: /src/kubify
    network_mode: host
    volumes:
      - ./:/src/kubify:cached
      - ~/kubify/kubedb.txt:/root/kubify/kubedb.txt:cached
    privileged: true
    command: ./docker-compose.sh
