version: "3.9"

services:
  kubify:
    build:
      network: host
    # ports:
    #   - "443:443"
    working_dir: /src/kubify
    network_mode: host
    # ports:
    #   - "127.0.0.1:62609:62609"
    volumes:
      - ./:/src/kubify
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.kube/config:/root/.kube/config
      # - ./._kubify_work/.aws:/root/.aws
      # - ./dev/*:/src/kubify/dev/*
      # - ./src/kubify/k8s/*:/src/kubify/src/kubify/k8s/
      # - ./src/kubify/tools/*:/src/kubify/src/kubify/tools/
    privileged: true
    command: ./docker-compose.sh
