version: "3.9"

services:
  kubify:
    build:
      network: host
    working_dir: /var/folders
    network_mode: host
    volumes:
      - $PWD/:/var/folders:cached
    privileged: true
    command: ./docker-compose.sh
