version: "3.9"

services:
  kubify:
    build:
      network: host
    working_dir: /src/kubify
    network_mode: host
    volumes:
      - ./:/src/kubify # if devcontainer only, can also add :cached
      - ~/kubify/kubedb.txt:/root/kubify/kubedb.txt # if devcontainer only, can also add :cached
    privileged: true
    command: ./docker-compose.sh
