version: "3.9"

services:
  kubify:
    build:
      network: host
    working_dir: /src/kubify
    network_mode: host
    volumes:
      - ./:/src/kubify
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.kube/config:/root/.kube/config
      - ~/kubify/kubedb.txt:/root/kubify/kubedb.txt
    privileged: true
    command: ./docker-compose.sh
