---
apiVersion: k8.kubify.local/v1
kind: Config
metadata:
  name: example-tensorflow-gpu-cpu-svc
services:
  example-tensorflow-cpu-svc:

dev:
  sync:
    'cpu/***': 'app/'
  scripts:
    start: |
      echo 'listening for code changes in example-tensorflow-gpu-cpu-svc cpu folder'
      python3 tensorflow-cpu.py
release:
  scripts:
    start: |
      echo 'starting example-tensorflow-gpu-cpu-svc cpu release service's pod'  
      python3 tensorflow-cpu.py
config:
  ENV: "{{ env }}"
  KUBIFY_ENV: "{{ env }}"
profiles:
  dev:
    scaler:
      minReplicas: 1
      maxReplicas: 10
      metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 90
    resources:
      requests:
        cpu: 8m
        memory: 8Mi
      limits:
        cpu: 512m
        memory: 512Mi
    
