# spec example usage https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2
env:
  variables:
    KUBIFY_CI: 1
    KUBIFY_CONTAINER_REGISTRY: ecr
    # should be unique ("os" should be changed to your company acronym):
    UNIQUE_COMPANY_ACRONYM: os
    KUBIFY_DEBUG: 0
phases:
  eks_clusters:
    commands:
      - pwd
      - env | grep KUBIFY
      - echo "TODO eksctl command loop run here"
  k8s_services:
    commands:
      - pwd
      - env | grep KUBIFY
      - echo "TODO services deploy loop run here"
cache:
  paths:
    - "**/node_modules"
    - "**/site-packages"