---
apiVersion: k8.kubify.local/v1
kind: Config
metadata:
  name: kafka-svc
service:
  port: "9092"
config:
    KAFKA_ADVERTISED_HOST_NAME: "kafka-svc.demo.svc"
    KAFKA_CREATE_TOPICS: "LinkClick:4:1"
    KAFKA_ZOOKEEPER_CONNECT: "zookeeper-svc.demo.svc:2181"
    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,SASL_SSL:SASL_SSL,SASL_SSL_HOST:SASL_SSL"
    KAFKA_LISTENERS: "PLAINTEXT://:9092,SASL_SSL://:9093"
    KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-svc.demo.svc:9092,SASL_SSL://kafka-svc.demo.svc:9093"
    KAFKA_SSL_KEYSTORE_LOCATION: '/certs/kafka.server.keystore.jks'
    KAFKA_SSL_KEYSTORE_PASSWORD: '5678985-Z'
    KAFKA_SSL_KEY_PASSWORD: '5678985-Z'
    KAFKA_SSL_TRUSTSTORE_LOCATION: '/certs/kafka.server.truststore.jks'
    KAFKA_SSL_TRUSTSTORE_PASSWORD: '5678985-Z'
    KAFKA_SSL_CLIENT_AUTH: 'required'
    KAFKA_SASL_ENABLED_MECHANISMS: 'PLAIN'
    KAFKA_OPTS: ' -Djava.security.auth.login.config=/root/config/kafka_server_jaas.conf'
    AWS_ACCESS_KEY_ID: 'test'
    AWS_SECRET_ACCESS_KEY: 'test'
    AWS_DEFAULT_REGION: 'us-east-1'
    # KAFKA_OPTS: ' -Daws.custom.endpoint=http://localstack-aws-svc.demo.svc:4566 -Djava.security.auth.login.config=/root/config/kafka_server_jaas.conf'
aws:
  s3:
    - 
        Name: "kubify-{{ env }}-kafka-svc"  
    - 
        Name: "kubify-{{ env }}-2-kafka-svc"
depends_on:
  - zookeeper-svc
internal:
  tcp:
    - 9092
    - 9093
profiles:
  dev:
    scaler:
      minReplicas: 1
      maxReplicas: 4
      metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 40
    resources:
      requests:
        cpu: 8m
        memory: 8Mi
      limits:
        cpu: 512m
        memory: 512Mi