---
apiVersion: k8.kubify.local/v1
kind: Config
metadata:
  name: example-django-simple-svc
init: |
  echo "run migrations for example-django-simple-svc/app"
  cd /app/app
  python manage.py makemigrations
  python manage.py migrate
dev:
  sync:
    'app/***': 'app/'
  scripts:
    start: |
      echo 'listening for code changes in example-django-simple-svc folder'
      cd /app/app
      python manage.py runserver  0.0.0.0:8000
release:
  scripts:
    start: |
      echo 'starting example-django-simple-svc release service's pod'  
      cd /app/app
      python manage.py runserver  0.0.0.0:8000
service:
  port: "8000"
config:
  PORT: "8000"
  APP_NAME: example-django-simple-svc
  DEBUG: "example-django-simple-svc:*"
  ENV: "{{ env }}"
  KUBIFY_ENV: "{{ env }}"
profiles:
  dev:
    scaler:
      minReplicas: 1
      maxReplicas: 4
      metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 40
    resources:
      requests:
        cpu: 8m
        memory: 8Mi
      limits:
        cpu: 512m
        memory: 512Mi
    
