# OPTIONAL
FROM willy0912/kubify:main

RUN apt install -y  --no-install-recommends python3.7 python3.8 python3.9 python3.10
RUN apt-get install -y python3.7 python3.8 python3.9 python3.10
RUN apt install -y python3.7-distutils python3.8-distutils python3.9-distutils python3.10-distutils
RUN apt install -y python3.7-dev python3.8-dev python3.9-dev python3.10-dev
RUN python3.7 -m pip install tox>=3.25.1
RUN python3.8 -m pip install tox>=3.25.1
RUN python3.9 -m pip install tox>=3.25.1
RUN python3.10 -m pip install tox>=3.25.1
RUN python3.7 -m pip install -U tox>=3.25.1
RUN python3.8 -m pip install -U tox>=3.25.1
RUN python3.9 -m pip install -U tox>=3.25.1
RUN python3.10 -m pip install -U tox>=3.25.1
RUN make pythons-cache
COPY . .
RUN make clean
RUN make pythons