---
apiVersion: k8.kubify.local/v1
kind: Config
metadata:
  name: example-node-svc
init: |
  echo "run init for example-node-svc/app"
dev:
  # TODO: have an option for alternate reloaders in start (such as hot reloading)
  # TODO: this should also have an option to run unit tests each time it reloads
  # "sync" = if you want Kubify to listen for code changes (other option is 
  # using some cli listener for code changes in release.scripts.start)
  sync:
    'app/***': 'app/'
  scripts:
    start: |
      echo 'listening for code changes in example-node-svc folder'
      cd /app/app
      node app.js
release:
  scripts:
    start: |
      echo 'starting example-node-svc release service's pod'  
      cd /app/app
      node app.js
service:
  port: "3000"
config:
  PORT: "3000"
  APP_NAME: example-node-svc
  DEBUG: "example-node-svc:*"
  ENV: "{{ env }}"
  KUBIFY_ENV: "{{ env }}"
profiles:
  dev:
    scaler:
      minReplicas: 2
      maxReplicas: 4
      metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 40
    resources:
      requests:
        cpu: 64m
        memory: 64Mi
      limits:
        cpu: 128m
        memory: 128Mi
    
