---
apiVersion: k8.kubify.local/v1
kind: Config
metadata:
  name: zookeeper-svc
service:
  port: "2181"
config:
  ZOOKEEPER_CLIENT_PORT: '2181'
  ZOOKEEPER_TICK_TIME: '2000'
  JVMFLAGS: ' -Djava.security.auth.login.config=/root/config/zookeeper_jaas.conf -Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider'
internal:
  tcp:
  - 2181
  - 2888
  - 3888
profiles:
  dev:
      requests:
        cpu: 8m
        memory: 8Mi
      limits:
        cpu: 512m
        memory: 512Mi
