---
apiVersion: k8.kubify.local/v1
kind: Config
metadata:
  name: example-java-svc
init: |
  echo "run migrations for example-java-svc/app"
depends_on:
  - zookeeper-svc
dev:
  # "sync" is if you want Kubify to listen for code changes (other option is 
  # using some cli listener for code changes in release.scripts.start)
  sync:
    'app/***': 'app/'
  scripts:
    start: |
      echo 'listening for code changes in example-java-svc folder'
      cd /app
      ./mvnw spring-boot:run
release:
  scripts:
    start: |
      echo 'starting example-java-svc release service's pod'  
      cd /app
      ./mvnw spring-boot:run
service:
  port: "8080"
config:
  PORT: "8080"
  APP_NAME: example-java-svc
  DEBUG: "example-java-svc:*"
  ENV: "{{ env }}"
  KUBIFY_ENV: "{{ env }}"
profiles:
  dev:
    scaler:
      minReplicas: 1
      maxReplicas: 4
      metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 40
    resources:
      requests:
        cpu: 8m
        memory: 8Mi
      limits:
        cpu: 512m
        memory: 512Mi
    
