version: '3.9'
services:
  kubify:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/:/var/folders:cached
      - $HOME/kubify/kubedb.txt:/root/kubify/kubedb.txt:cached
      - $HOME/.aws:/root/.aws:cached
      - $HOME/.ssh:/root/.ssh:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    # uncomment for rtx datascience
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]