# The DataScience Kubify MLOps Toolkit

---
apiVersion: k8.kubify.local/v1
kind: Config
metadata:
  name: kubify-mlops-toolkit

# helm native
helm:
  # operators deploy before charts
  operators:
      # also used for: dask on ray
      # also used for: spark on ray
    - kuberay-operator
    - sagemaker-operator
  charts:
    - argo-cd
    - argo-workflows
    - blazingsql
    - cloudshell
    - determined-helm-chart
    - prefect
    - data-profiler
    - delta-sharing-server
    - elastic
    - fastai
    - hive-metastore
    - jena
    - jupyter
    - kafka
    - label-studio
    - library-chart
    - mariadb
    - mlflow
    - airflow
    - runai-backend
    - runai-backend
    - mongodb
    - neo4j
    - nocodb
    - openrefine
    - pgadmin
    - pinot
    # timescaledb
    - postgresql
    - kube-prometheus-stack
    - tensorflow
    - pytorch
    - rapidsai
    - ray-cluster
    - rstudio
    - vscode
  k8s-custom-resource-j2:
    - tests/fixture_kubeflow.j2
    - tests/fixture_kuberay.j2
    - tests/fixture_spark_on_ray.j2
    - tests/fixture_dask_on_ray.j2

dags:
    # looks in ./dags folder
    - example