---
apiVersion: k8.kubify.local/v1
kind: Config
metadata:
  name: localstack-aws-svc
service:
  port: "4566"

# NOTE: do not put a depends_on on localstack-aws-svc (the only service with this restriction)

config:
  # simulate any AWS service: https://github.com/localstack/localstack
  # DEFAULT_REGION: us-east-1
  SERVICES: "iam,sts,sns,lambda,s3,sqs,redshift,ssm,cloudformation,ecr,apigateway"
  # note: or use docker-reuse to make lambda better and have better performance (but have to figure out skaffold if so)
  LAMBDA_EXECUTOR: "local"
  # LAMBDA_EXECUTOR: "docker-reuse"
  # LAMBDA_DOCKER_FLAGS: " -e PYTHONPATH='/var/task:/opt/python:/var/task/python/lib/python3.7/site-packages:/opt/python/lib/python3.7/site-packages:/var/task/node_modules' --network host "
  # DEBUG: "localstack-aws-svc:*"
  # DOCKER_HOST: unix:///var/run/docker.sock
  # LAMBDA_DOCKER_NETWORK: bridge
  # LAMBDA_REMOTE_DOCKER: 1
  DEBUG: "true"
  # PYTHONPATH: "/var/task/{REL_PATH_TO_PYTHON_PACKAGES}:/var/task/{REL_PATH_TO_PYTHON_PACKAGES}/python/lib/python3.7/site-packages:/opt/code/localstack/.venv/lib/python3.8/site-packages:/opt/code/localstack/.venv/lib/python3.7/site-packages"

internal:
  tcp:
    - 4566
    # - 45975
profiles:
  dev:
    resources:
      requests:
        cpu: 8m
        memory: 8Mi
      limits:
        cpu: 512m
        memory: 512Mi

