name: Docker PyPi CI

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    # - name: Run on architecture for multiarch
    #   uses: uraimo/run-on-arch-action@v2.2.0
    #   arch: arm64,amd64
    - name: actions/checkout
      uses: actions/checkout@v2
      with:
          persist-credentials: false
    # docker build multi-arch setup
    -
      name: setup-qemu-multiarch
      uses: docker/setup-qemu-action@v2
    -
      name: setup-biuldx-multiarch
      uses: docker/setup-buildx-action@v2
    - name: pypi-make-package
      id: makepypipackage
      run: python3 setup.py sdist bdist_wheel
    # pypi package ship
    - name: release-pypi
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
    -
      name: login-dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    # dockerhub image build security package ship
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: ./
        # file: ./Dockerfile
        file: ./dockers/Dockerfile-cached
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: willy0912/kubify-local:main