name: Docker PyPi CI

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: actions/checkout
      uses: actions/checkout@v2
      with:
          persist-credentials: false
    - name: pypi-make-package
      id: makepypipackage
      run: apt update && apt install -y make && make package
    # pypi package ship
    - name: release-pypi
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
    # docker build multi-arch setup
    -
      name: setup-qemu-multiarch
      uses: docker/setup-qemu-action@v2
    -
      name: setup-biuldx-multiarch
      uses: docker/setup-buildx-action@v2
    -
      name: login-dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    # dockerhub image build security package ship
    -
      name: release-dockerhub
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: willy0912/kubify-local:main