name: Docker All Python Versions

on:
  push:
    branches: [ "docker-all-pythons" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: actions/checkout
      uses: actions/checkout@v2
      with:
          persist-credentials: false
    -
      name: setup-qemu-multiarch
      uses: docker/setup-qemu-action@v2
    -
      name: setup-biuldx-multiarch
      uses: docker/setup-buildx-action@v2
    -
      name: login-dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: ./
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: willy0912/kubify:main
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: ./
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: willy0912/kubify:main