name: Cross-Platform NoArch Docker PyPi Conda Test Release CICD Workflow
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: actions/checkout
      uses: actions/checkout@v2
      with:
          persist-credentials: false
    # conda build, test and ship
    - name: Build and publish Conda packages to Anaconda.org
      description: 'https://anaconda.org/conda-forge/kubify'
      uses: amauryval/publish_conda_package_action@2.0.3
      with:
        CondaDir: 'conda'
        Channels: 'conda-forge defaults' 
        Platforms: 'noarch'
        CondaUsername: ${{ secrets.CONDA_USERNAME }}
        CondaPassword: ${{ secrets.CONDA_PASSWORD }}
    # dockers build multi-arch setup
    -
      name: setup-qemu-multiarch-arm-amd
      uses: docker/setup-qemu-action@v2
    -
      name: setup-buildx-multiarch-arm-amd
      uses: docker/setup-buildx-action@v2
    - name: pypi-make-package
      id: makepypipackage
      run: python3 setup.py sdist bdist_wheel
    # dockerhub build, test and ship image
    -
      name: login-dockerhub-registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    # docker arm/amd images build security test package
    -
      name: Build and Publish Docker Image to DockerHub
      description: 'https://hub.docker.com/repository/docker/willy0912/kubify'
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/aarch64
        push: ${{ github.event_name != 'pull_request' }}
        tags: willy0912/kubify:main
    # pypi build, test and ship package
    - name: Build and Publish to PyPi.org
      description: 'https://pypi.org/project/kubify'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}