name: docker-pypi-gitops-push
on:
  push:
    branches:
      - 'main' # release branch of approved pr that is merged and tagged (with :main tag)
      - 'kubify-9001' # testing docker release cicd in this branch (origin/kubify-9001)
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: get-version
        id: getversion
        run: echo "::set-output name=version::$(cat __version__)"
      # docker build multi-arch setup
      -
        name: setup-qemu-multiarch
        uses: docker/setup-qemu-action@v2
      -
        name: setup-biuldx-multiarch
        uses: docker/setup-buildx-action@v2
      -
        name: login-dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # dockerhub image build security package push
      -
        name: release-dockerhub
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: willy0912/kubify-local:v${{ steps.getversion.outputs.version }}
      # pypi package build package checks tests push
      - name: release-pypi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}